version: '3.6'

services:
  central_api:
    build:
      dockerfile: ./Dockerfile-dev
      context: ./api
    container_name: central_xiaomi_api_dev
    image: central_xiaomi_api
    command:  "npm run dev"
    volumes:
      - ./api:/app
      - ./api/node_modules:/app/node_modules
      - ./api/central.db:/app/central.db
    ports:
      - 9615:9615
      - 3001:3001
  central_client:
    build:
      dockerfile: ./Dockerfile-dev
      context: ./client
    container_name: central_xiaomi_client_dev
    command: "npm run start"
    environment:
      - "NODE_ENV=development"
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    image: central_xiaomi_client
    ports:
      - 3000:3000
    # extra_hosts:
    #   - "outside:${HOST_IP}"
