version: '3.6'
services:
  central-reverse-proxy:
    image: traefik # The official Traefik docker image
    container_name: central_xiaomi_proxy
    command: --api --docker.exposedbydefault=false # Enables the web UI and tells Træfik to listen to docker, without exposing by default
    ports:
      - "80:80"     # The HTTP port
      - "8081:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
  central:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: central_xiaomi
    image: central_xiaomi
    ports:
      - "${API_PORT}:${API_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:central.api.localhost.tv"
    extra_hosts:
      - "outside:${HOST_IP}"
    volumes:
    - ./src/server/central.db:/server/central.db
    - ./src/server/central.db-journal:/server/central.db-journal
  central_client:
    build:
      dockerfile: Dockerfile_client
      context: .
    container_name: central_xiaomi_client
    image: central_xiaomi_client
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:central.localhost.tv"
    extra_hosts:
      - "outside:${HOST_IP}"