version: '3.6'

services:
  central:
    build:
      dockerfile: Dockerfile-dev
      context: .
    container_name: central_xiaomi_dev
    command: "npm run docker-dev"
    volumes:
      - ./src/server:/app/server
      - ./ecosystem.config.js:/src/ecosystem.config.js
    ports:
      - 9615:9615
      - 3000:3000
