version: '3.6'
services:
  central:
    build:
      dockerfile: ./api/Dockerfile
      context: .
    container_name: central_xiaomi
    image: central_xiaomi
    ports:
      - "${API_PORT}:${API_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:central.api.localhost.tv"
    extra_hosts:
      - "outside:${HOST_IP}"
    volumes:
      - ./src/server/central.db:/app/central.db
    ports :
      - 3001:3001
  central_client:
    build:
      dockerfile: ./client/Dockerfile
      context: .
    container_name: central_xiaomi_client
    image: central_xiaomi_client
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:central.localhost.tv"
    extra_hosts:
      - "outside:${HOST_IP}"
