version: '3.6'
services:
  central:
    build:
      dockerfile: ./src/server/Dockerfile
      context: .
    container_name: central_xiaomi
    image: central_xiaomi
    ports:
      - "${API_PORT}:${API_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:central.api.localhost.tv"
    extra_hosts:
      - "outside:${HOST_IP}"
    volumes:
      - ./src/server/central.db:/app/central.db
    ports :
      - 3001:3001
  # central_client:
  #   build:
  #     dockerfile: Dockerfile_client
  #     context: .
  #   container_name: central_xiaomi_client
  #   image: central_xiaomi_client
  #   ports:
  #     - "${FRONT_PORT}:${FRONT_PORT}"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.frontend.rule=Host:central.localhost.tv"
  #   extra_hosts:
  #     - "outside:${HOST_IP}"