version: '3.6'

services:
  central:
    build:
      dockerfile: Dockerfile-dev
      context: .
    container_name: central_xiaomi_dev
    command: "npm run docker-dev"
    volumes:
      - ./src/server:/app/server
